version: '3.9'

services:
  frontend:
    image: node:latest
    container_name: frontend-logcomex
    ports:
      - 4000:4000
    restart: always
    volumes:
      - ./frontend:/app
    depends_on:
      - api
    tty: true
    working_dir: /app
    networks:
      - lognet

  api:
    image: logcomex/api-php
    build:
      context: ./docker/php
    container_name: api-logcomex
    ports:
      - 8000:8000
    restart: always
    volumes:
      - ./api:/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini-development
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini-production
    depends_on:
      - database
    tty: true
    networks:
      - lognet
    links:
      - "database"

  database:
    image: mariadb:latest
    container_name: database-logcomex
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: logcomex
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - lognet


networks:
  lognet:

volumes:
  db-data:




